import type { SupportedLanguage } from "@/locales/i18n-provider";

type TopicTitleMap = Record<string, string>;

const TOPIC_TITLES_BY_LANGUAGE: Record<SupportedLanguage, TopicTitleMap> = {
	"uz-Latn": {
		"1": "Umumiy qoidalar",
		"2": "Haydovchilarning umumiy vazifalari",
		"3": "Piyodalarning majburiyatlari",
		"4": "Maxsus transport vositalarining imtiyozlari",
		"5": "Svetofor ishoralari",
		"6": "Tartibga soluvchining ishoralari",
		"7": "Ogohlantiruvchi va avariya (xavf-xatar) ishoralari",
		"8": "Harakatlanishni boshlash, manyovr qilish",
		"9": "Yo'lning qatnov qismida transport vositalarining joylashuvi",
		"10": "Harakatlanish tezligi",
		"11": "Quvib o'tish",
		"12": "To'xtash va to'xtab turish",
		"13": "Chorrahalarda harakatlanish",
		"14": "Tartibga solingan chorrahalar",
		"15": "Tartibga solinmagan chorrahalar asosiy yo'l yo'nalishi to'g'riga",
		"16": "Tartibga solinmagan chorrahalar teng ahamiyatli",
		"17": "Tartibga solinmagan chorrahalar asosiy yo'l yo'nalishi o'zgarishi",
		"18": "Piyodalarning o'tish joylari va yo'nalishli transport vositalarining bekatlari",
		"19": "Temir yo'l kesishmalari orqali harakatlanish",
		"20": "Avtomagistrallarda harakatlanish",
		"21": "Turar joy dahalarida harakatlanish",
		"22": "Tik balandlik va nishabliklarda harakatlanish",
		"23": "Yo'nalishli transport vositalarining imtiyozlari",
		"24": "Tashqi yoritish asboblaridan foydalanish",
		"25": "Mexanik transport vositalarini shatakka olish",
		"26": "Transport vositalarini boshqarishni o'rgatish",
		"27": "Odam tashish",
		"28": "Yuk tashish",
		"29": "Velosiped, moped va aravalar harakatlanishiga doir qo'shimcha talablar",
		"30": "Mansabdor shaxslar va fuqarolarning yo'l harakati xavfsizligini ta'minlash majburiyatlari",
		"31": "Ogohlantiruvchi belgilar",
		"32": "Imtiyoz belgilari",
		"33": "Taqiqlovchi belgilar",
		"34": "Buyuruvchi belgilar",
		"35": "Axborot-ko'rsatgich belgilari",
		"36": "Servis belgilari",
		"37": "Qo'shimcha axborot belgilari",
		"38": "Yotiq chiziqlar",
		"39": "Tik chiziqlar",
		"40": "Transport vositalaridan foydalanishni taqiqlovchi shartlar",
		"41": "Harakat xavfsizligi asoslari",
		"42": "Birinchi tibbiy yordam",
	},
	"uz-Cyrl": {
		"1": "Умумий қоидалар",
		"2": "Ҳайдовчиларнинг умумий вазифалари",
		"3": "Пиёдаларнинг мажбуриятлари",
		"4": "Махсус транспорт воситаларининг имтиёзлари",
		"5": "Светофор ишоралари",
		"6": "Тартибга солувчининг ишоралари",
		"7": "Огоҳлантирувчи ва авария (хавф-хатар) ишоралари",
		"8": "Ҳаракатланишни бошлаш, манёвр қилиш",
		"9": "Йўлнинг қатнов қисмида транспорт воситаларининг жойлашуви",
		"10": "Ҳаракатланиш тезлиги",
		"11": "Қувиб ўтиш",
		"12": "Тўхташ ва тўхтаб туриш",
		"13": "Чорраҳаларда ҳаракатланиш",
		"14": "Тартибга солинган чорраҳалар",
		"15": "Тартибга солинмаган чорраҳалар асосий йўл йўналиши тўғрига",
		"16": "Тартибга солинмаган чорраҳалар тенг аҳамиятли",
		"17": "Тартибга солинмаган чорраҳалар асосий йўл йўналиши ўзгариши",
		"18": "Пиёдаларнинг ўтиш жойлари ва йўналишли транспорт воситаларининг бекатлари",
		"19": "Темир йўл кесишмалари орқали ҳаракатланиш",
		"20": "Автомагистралларда ҳаракатланиш",
		"21": "Турар жой даҳаларида ҳаракатланиш",
		"22": "Тик баландлик ва нишабликларда ҳаракатланиш",
		"23": "Йўналишли транспорт воситаларининг имтиёзлари",
		"24": "Ташқи ёритиш асбобларидан фойдаланиш",
		"25": "Механик транспорт воситаларини шатакка олиш",
		"26": "Транспорт воситаларини бошқаришни ўргатиш",
		"27": "Одам ташиш",
		"28": "Юк ташиш",
		"29": "Велосипед, мопед ва аравалар ҳаракатланишига доир қўшимча талаблар",
		"30": "Мансабдор шахслар ва фуқароларнинг йўл ҳаракати хавфсизлигини таъминлаш мажбуриятлари",
		"31": "Огоҳлантирувчи белгилар",
		"32": "Имтиёз белгилари",
		"33": "Тақиқловчи белгилар",
		"34": "Буюрувчи белгилар",
		"35": "Ахборот-кўрсатгич белгилари",
		"36": "Сервис белгилари",
		"37": "Қўшимча ахборот белгилари",
		"38": "Ётиқ чизиқлар",
		"39": "Тик чизиқлар",
		"40": "Транспорт воситаларидан фойдаланишни тақиқловчи шартлар",
		"41": "Ҳаракат хавфсизлиги асослари",
		"42": "Биринчи тиббий ёрдам",
	},
	ru: {
		"1": "Общие правила",
		"2": "Общие обязанности водителей",
		"3": "Обязанности пешеходов",
		"4": "Привилегии специальных транспортных средств",
		"5": "Сигналы светофора",
		"6": "Сигналы регулировщика",
		"7": "Предупредительные и аварийные сигналы",
		"8": "Начало движения и маневрирование",
		"9": "Расположение транспортных средств на проезжей части",
		"10": "Скорость движения",
		"11": "Обгон",
		"12": "Остановка и стоянка",
		"13": "Движение через перекрестки",
		"14": "Регулируемые перекрестки",
		"15": "Нерегулируемые перекрестки: главное направление прямо",
		"16": "Нерегулируемые перекрестки равнозначных дорог",
		"17": "Нерегулируемые перекрестки: изменение направления главной дороги",
		"18": "Пешеходные переходы и остановки маршрутных транспортных средств",
		"19": "Движение через железнодорожные переезды",
		"20": "Движение по автомагистралям",
		"21": "Движение в жилых зонах",
		"22": "Движение на крутых подъемах и спусках",
		"23": "Приоритет маршрутных транспортных средств",
		"24": "Пользование внешними световыми приборами",
		"25": "Буксировка механических транспортных средств",
		"26": "Обучение вождению",
		"27": "Перевозка людей",
		"28": "Перевозка грузов",
		"29": "Дополнительные требования к движению велосипедов, мопедов и гужевых повозок",
		"30": "Обязанности должностных лиц и граждан по обеспечению безопасности дорожного движения",
		"31": "Предупреждающие знаки",
		"32": "Знаки приоритета",
		"33": "Запрещающие знаки",
		"34": "Предписывающие знаки",
		"35": "Информационно-указательные знаки",
		"36": "Знаки сервиса",
		"37": "Знаки дополнительной информации",
		"38": "Горизонтальная разметка",
		"39": "Вертикальная разметка",
		"40": "Условия, при которых запрещается эксплуатация транспортных средств",
		"41": "Основы безопасности движения",
		"42": "Первая медицинская помощь",
	},
};

export function getLocalizedTopicTitle(language: SupportedLanguage, topicId: string) {
	const map = TOPIC_TITLES_BY_LANGUAGE[language];
	return map[topicId] ?? null;
}
