# Generated by Django 6.0.4 on 2026-05-02 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0007_alter_examsession_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contest_type', models.CharField(choices=[('global', 'Global'), ('academy', 'Akademiya')], default='global', max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('active', 'Faol'), ('finished', 'Tugagan')], default='upcoming', max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('entry_token', models.PositiveIntegerField(default=0)),
                ('question_count', models.PositiveIntegerField(default=20)),
                ('time_limit', models.PositiveIntegerField(default=20)),
                ('question_source', models.CharField(choices=[('custom', "Qo'lda tanlangan"), ('category', 'Kategoriya asosida')], default='category', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='quiz.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, to='quiz.question')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contestlar',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('token_spent', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('wrong_count', models.PositiveIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.PositiveIntegerField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qatnashuvchi',
                'verbose_name_plural': 'Qatnashuvchilar',
                'ordering': ['rank', '-correct_count'],
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contests.contestparticipant')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
