# Generated by Django 6.0.4 on 2026-05-05 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='access_key',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Kirish kaliti'),
        ),
        migrations.AddField(
            model_name='contest',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Bir martalik'), ('daily', 'Kunlik'), ('weekly', 'Haftalik')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='AcademyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Akademiya nomi')),
                ('master_key', models.CharField(max_length=8, unique=True, verbose_name='Master kalit')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Akademiya profili',
                'verbose_name_plural': 'Akademiya profillari',
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='academy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='contests.academyprofile'),
        ),
    ]
