"""
Management command: python manage.py load_signs

signs_z/ va rules_r/ papkasidagi rasmlarni media/signs/ ga ko'chirib,
SignSection va Sign modellarini to'ldiradi.

Bo'limlar:
  z1-z7  — rasmiy 7 belgi turkumi (Yo'l harakati qoidalari 1-ilova)
  z8     — vaqtincha (sariq) yo'l belgilari
  z9     — svetofor ishoralari
  z10    — tartibga soluvchi ishoralari
  z11    — transport vositalarining taniqlik belgilari
  r1     — gorizontal yo'l chiziqlari (2-ilova)
  r2     — vertikal yo'l chiziqlari (2-ilova)
"""
import os
import shutil
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

from signs.models import Sign, SignSection

# ─── Bo'limlar ───────────────────────────────────────────────────────────────
SECTIONS = [
    {
        'order': 1, 'prefix': 'z1',
        'name_uzl': "Ogohlantiruvchi belgilar",
        'name_uzk': "Огоҳлантирувчи белгилар",
        'name_ru':  "Предупреждающие знаки",
    },
    {
        'order': 2, 'prefix': 'z2',
        'name_uzl': "Imtiyoz belgilari",
        'name_uzk': "Имтиёз белгилари",
        'name_ru':  "Знаки приоритета",
    },
    {
        'order': 3, 'prefix': 'z3',
        'name_uzl': "Taqiqlovchi belgilar",
        'name_uzk': "Тақиқловчи белгилар",
        'name_ru':  "Запрещающие знаки",
    },
    {
        'order': 4, 'prefix': 'z4',
        'name_uzl': "Buyuruvchi belgilar",
        'name_uzk': "Буюрувчи белгилар",
        'name_ru':  "Предписывающие знаки",
    },
    {
        'order': 5, 'prefix': 'z5',
        'name_uzl': "Axborot-ko'rsatgich belgilari",
        'name_uzk': "Ахборот-кўрсатгич белгилари",
        'name_ru':  "Информационно-указательные знаки",
    },
    {
        'order': 6, 'prefix': 'z6',
        'name_uzl': "Servis belgilari",
        'name_uzk': "Сервис белгилари",
        'name_ru':  "Знаки сервиса",
    },
    {
        'order': 7, 'prefix': 'z7',
        'name_uzl': "Qo'shimcha axborot belgilari",
        'name_uzk': "Қўшимча ахборот белгилари",
        'name_ru':  "Знаки дополнительной информации",
    },
    {
        'order': 8, 'prefix': 'z8',
        'name_uzl': "Vaqtincha yo'l belgilari",
        'name_uzk': "Вақтинча йўл белгилари",
        'name_ru':  "Временные дорожные знаки",
    },
    {
        'order': 9, 'prefix': 'z9',
        'name_uzl': "Svetofor ishoralari",
        'name_uzk': "Светофор ишоралари",
        'name_ru':  "Сигналы светофора",
    },
    {
        'order': 10, 'prefix': 'z10',
        'name_uzl': "Tartibga soluvchi ishoralari",
        'name_uzk': "Тартибга солувчи ишоралари",
        'name_ru':  "Сигналы регулировщика",
    },
    {
        'order': 11, 'prefix': 'z11',
        'name_uzl': "Transport vositalarining taniqlik belgilari",
        'name_uzk': "Транспорт воситаларининг танықлик белгилари",
        'name_ru':  "Опознавательные знаки транспортных средств",
    },
    {
        'order': 12, 'prefix': 'r1',
        'name_uzl': "Gorizontal yo'l chiziqlari",
        'name_uzk': "Горизонтал йўл чизиқлари",
        'name_ru':  "Горизонтальная дорожная разметка",
    },
    {
        'order': 13, 'prefix': 'r2',
        'name_uzl': "Vertikal yo'l chiziqlari",
        'name_uzk': "Вертикал йўл чизиқлари",
        'name_ru':  "Вертикальная дорожная разметка",
    },
]

# ─── Yo'l belgilari (z1–z11) ─────────────────────────────────────────────────
SIGNS = {
    # ── 1. Ogohlantiruvchi ────────────────────────────────────────────────────
    '1.1':    ("Shlagbaumli temir yo'l kesishmasi",
               "Shlagbaum bilan jihozlangan temir yo'l kesishmasiga yaqinlashayotganlikni bildiradi."),
    '1.2':    ("Shlagbaumsiz temir yo'l kesishmasi",
               "Shlagbaum bilan jihozlanmagan temir yo'l kesishmasiga yaqinlashayotganlikni bildiradi."),
    '1.3.1':  ("Bir izli temir yo'l",
               "Bir izli temir yo'l kesishmasi, shlagbaumsiz."),
    '1.3.2':  ("Ko'p izli temir yo'l",
               "Ikki va undan ortiq izli temir yo'l kesishmasi, shlagbaumsiz."),
    '1.4.1':  ("Temir yo'l kesishmasiga yaqinlashuv",
               "Aholi punktlaridan tashqarida temir yo'l kesishmasiga yaqinlashayotganlik haqida birinchi ogohlantirish."),
    '1.4.2':  ("Temir yo'l kesishmasiga yaqinlashuv",
               "Aholi punktlaridan tashqarida temir yo'l kesishmasiga yaqinlashayotganlik haqida ikkinchi ogohlantirish."),
    '1.4.3':  ("Temir yo'l kesishmasiga yaqinlashuv",
               "Aholi punktlaridan tashqarida temir yo'l kesishmasiga yaqinlashayotganlik haqida uchinchi ogohlantirish."),
    '1.4.4':  ("Temir yo'l kesishmasiga yaqinlashuv (qarama-qarshi, 1)",
               "Yo'lning chap tomoniga o'rnatilgan birinchi ogohlantirish belgisi."),
    '1.4.5':  ("Temir yo'l kesishmasiga yaqinlashuv (qarama-qarshi, 2)",
               "Yo'lning chap tomoniga o'rnatilgan ikkinchi ogohlantirish belgisi."),
    '1.4.6':  ("Temir yo'l kesishmasiga yaqinlashuv (qarama-qarshi, 3)",
               "Yo'lning chap tomoniga o'rnatilgan uchinchi ogohlantirish belgisi."),
    '1.5':    ("Tramvay yo'li bilan kesishuv",
               "Tramvay yo'li bilan kesishuv joyi."),
    '1.6':    ("Teng ahamiyatli yo'llar kesishuvi",
               "Teng ahamiyatli yo'llar kesishuviga yaqinlashayotganlikni bildiradi."),
    '1.7':    ("Aylanma harakatlanish bilan kesishuv",
               "Aylanma harakatlanish tartibida ishlatiladigan chorrahaga yaqinlashayotganlikni bildiradi."),
    '1.8':    ("Svetofor bilan tartibga solish",
               "Harakatlanish svetofor bilan tartibga solinadigan chorraha, piyodalar o'tish joyi yoki yo'l qismini bildiradi."),
    '1.9':    ("Ko'tarma ko'prik",
               "Ko'tarma ko'prik yoki solda kesib o'tish."),
    '1.10':   ("Sohilga chiqish",
               "Daryo yoki suv havzasi qirg'og'iga chiqishni bildiradi."),
    '1.11.1': ("Xavfli burilish (o'ngga)",
               "Yo'lning kichik radiusli yoki ko'rinishi cheklangan o'ngga burilish joyini bildiradi."),
    '1.11.2': ("Xavfli burilish (chapga)",
               "Yo'lning kichik radiusli yoki ko'rinishi cheklangan chapga burilish joyini bildiradi."),
    '1.12.1': ("Xavfli burilishlar (birinchi o'ngga)",
               "Yo'lning xavfli burilishlari bo'lgan qismini bildiradi, birinchi burilish o'ngga."),
    '1.12.2': ("Xavfli burilishlar (birinchi chapga)",
               "Yo'lning xavfli burilishlari bo'lgan qismini bildiradi, birinchi burilish chapga."),
    '1.13':   ("Tik nishablik",
               "Yo'lning tik nishabli qismiga yaqinlashayotganlikni bildiradi."),
    '1.14':   ("Tik balandlik",
               "Yo'lning tik balandlikli qismiga yaqinlashayotganlikni bildiradi."),
    '1.15':   ("Sirpanchiq yo'l",
               "Qatnov qismi o'ta sirpanchiq bo'lgan yo'l qismi."),
    '1.16':   ("Notekis yo'l",
               "Qatnov qismi notekis bo'lgan yo'l: o'nqir-cho'nqir, o'ydim-chuqur joylar, ko'prikning yo'lga notekis tutashuvi."),
    '1.17':   ("Tosh otilishi xavfi",
               "Transport vositasining g'ildiragi ostidan shag'al, tosh va shunga o'xshashlarning otilib chiqish ehtimoli."),
    '1.18.1': ("Yo'lning torayishi (ikki tomonlama)",
               "Qatnov qismining ikki tomondan torayishini bildiradi."),
    '1.18.2': ("Yo'lning torayishi (o'ngdan)",
               "Qatnov qismining o'ng tomondan torayishini bildiradi."),
    '1.18.3': ("Yo'lning torayishi (chapdan)",
               "Qatnov qismining chap tomondan torayishini bildiradi."),
    '1.19':   ("Ikki tomonlama harakatlanish",
               "Yo'lning (qatnov qismining) qarama-qarshi harakatlanish qismi boshlanishini bildiradi."),
    '1.20':   ("Piyodalar o'tish joyi",
               "Belgilar va yo'l chiziqlari bilan belgilangan piyodalar o'tish joyini bildiradi."),
    '1.21':   ("Bolalar",
               "Bolalar muassasasiga yaqin yo'lda bolalarning chiqib qolish ehtimolini bildiradi."),
    '1.22':   ("Velosiped yo'lkasi bilan kesishuv",
               "Velosiped yo'lkasi bilan kesishuv joyi."),
    '1.23':   ("Ta'mirlash ishlari",
               "Yo'lda ta'mirlash ishlari olib borilayotgan qismini bildiradi."),
    '1.24':   ("Mol haydab o'tish",
               "Mol haydab o'tiladigan joy."),
    '1.25.1': ("Yovvoyi hayvonlar",
               "Yo'lga yovvoyi hayvonlar chiqib qolishi mumkin bo'lgan qismni bildiradi."),
    '1.25.2': ("Pastlab uchuvchi qushlar",
               "Yo'lga pastlab uchuvchi qushlar to'siq bo'lishi mumkin bo'lgan qismni bildiradi."),
    '1.25.3': ("Kemiruvchi va sudralib yuruvchi hayvonlar",
               "Yo'lda kemiruvchi va sudralib yuruvchi hayvonlar bo'lishi mumkin bo'lgan qismni bildiradi."),
    '1.26':   ("Toshlar tushishi",
               "Tosh ko'chishi, surilishi va tushishi mumkin bo'lgan yo'l qismini bildiradi."),
    '1.27':   ("Yonlama shamol",
               "Kuchli yonlama shamol bo'lishi mumkin bo'lgan yo'l qismini bildiradi."),
    '1.28':   ("Pastlab uchuvchi samolyotlar",
               "Samolyotlar pastlab uchib o'tadigan yo'l qismini bildiradi."),
    '1.29':   ("Tunnel",
               "Sun'iy ravishda yoritilmagan yoki kirish peshtog'ining ko'rinishi cheklangan tunnelni bildiradi."),
    '1.30':   ("Boshqa xavf-xatarlar",
               "Ogohlantiruvchi belgilarda ko'zda tutilmagan xavf-xatarlar bo'lgan yo'l qismini bildiradi."),
    '1.31':   ("Sun'iy yo'l notekisligi",
               "Yo'lning sun'iy notekislik o'rnatilgan qismiga yaqinlashayotganligi haqida ogohlantiradi."),
    '1.31.1': ("Burilishning yo'nalishi",
               "Kichik radiusli, ko'rinishi cheklangan yo'lda harakatlanish yo'nalishini bildiradi."),
    '1.31.2': ("Burilishning yo'nalishi",
               "Kichik radiusli, ko'rinishi cheklangan yo'lda harakatlanish yo'nalishini bildiradi."),
    '1.31.3': ("Burilishning yo'nalishi (T-simon)",
               "T-simon chorrahada yoki yo'l ayrilishlarida harakatlanish yo'nalishini bildiradi."),
    '1.32':   ("Tirbandlik",
               "Tirbandlik hosil bo'lgan yo'l yoki chorrahaga kirish oldidan o'rnatiladi."),
    '1.33':   ("Qatnov qismi kesishmasi hududi",
               "Chorrahaga yaqinlashayotganlikni anglatib, tirbandlik tufayli harakatlanishga to'sqinlik bo'lishi mumkinligini bildiradi."),
    '1.34':   ("Diqqat, boshqariladigan to'siq",
               "Boshqariladigan to'suvchi qurilmasiga yetmasdan o'rnatiladi."),
    '1.35':   ("Piyodalarning yo'l yoqasidan yurishi mumkin bo'lgan hudud",
               "Piyodalarning yo'l yoqasidan yurishi mumkin bo'lgan hududni bildiradi."),

    # ── 2. Imtiyoz ────────────────────────────────────────────────────────────
    '2.1':    ("Asosiy yo'l",
               "Harakat tartibga solinmagan chorrahalarda oldin o'tish huquqini beradi."),
    '2.2':    ("Asosiy yo'lning oxiri",
               "Asosiy yo'l maqomining tugashini bildiradi."),
    '2.3.1':  ("Ikkinchi darajali yo'l bilan kesishuv",
               "Ikkinchi darajali yo'l bilan kesishuvni bildiradi."),
    '2.3.2':  ("Ikkinchi darajali yo'l bilan tutashuv (o'ngdan)",
               "O'ng tomondan tutashuvchi ikkinchi darajali yo'l borligini bildiradi."),
    '2.3.3':  ("Ikkinchi darajali yo'l bilan tutashuv (chapdan)",
               "Chap tomondan tutashuvchi ikkinchi darajali yo'l borligini bildiradi."),
    '2.4':    ("Yo'l bering!",
               "Haydovchi kesib o'tilayotgan yo'ldan harakatlanayotgan transport vositasiga yo'l berishi kerak."),
    '2.5':    ("To'xtamasdan harakatlanish taqiqlangan",
               "To'xtash chizig'i oldida to'xtamasdan harakatlanish taqiqlanadi."),
    '2.6':    ("Ro'para harakatlanishning ustunligi",
               "Yo'lning tor qismiga kirish taqiqlanadi, ro'paradan kelayotgan transport vositasiga yo'l berish kerak."),
    '2.7':    ("Ro'paradagi harakatlanishga nisbatan imtiyoz",
               "Yo'lning tor qismida harakatlanishda haydovchi ro'paradan kelayotgan transport vositasiga nisbatan imtiyozga egaligini bildiradi."),

    # ── 3. Taqiqlovchi ────────────────────────────────────────────────────────
    '3.1':    ("Kirish taqiqlangan",
               "Barcha transport vositalarining kirishi taqiqlanishini bildiradi."),
    '3.2':    ("Harakatlanish taqiqlangan",
               "Barcha transport vositalarining harakatlanishi taqiqlanishini bildiradi."),
    '3.3':    ("Mexanik transport vositalarining harakatlanishi taqiqlangan",
               "Mexanik transport vositalarining harakatlanishi taqiqlanadi."),
    '3.4':    ("Yuk avtomobillarining harakatlanishi taqiqlangan",
               "Ruxsat etilgan to'liq vazni 3,5 tonnadan ortiq yuk avtomobillari va traktorlarning harakatlanishi taqiqlanadi."),
    '3.5':    ("Mototsikl va elektromototsikllar harakatlanishi taqiqlangan",
               "Mototsikl va elektromototsikllarning harakatlanishi taqiqlanadi."),
    '3.5.1':  ("Skuter va mopedlar harakatlanishi taqiqlangan",
               "Skuter va mopedlarning harakatlanishi taqiqlanadi."),
    '3.6':    ("Traktorlar harakatlanishi taqiqlangan",
               "Traktorlar va o'ziyurar uskunalarning harakatlanishi taqiqlanadi."),
    '3.7':    ("Tirkama bilan harakatlanish taqiqlangan",
               "Yuk avtomobillari va traktorlarning barcha turdagi tirkamalar bilan harakatlanishi va shatakka olish taqiqlanadi."),
    '3.8':    ("Ot-arava harakatlanishi taqiqlangan",
               "Ot-arava, otliqlar, yuk ortilgan hayvonlarning harakatlanishi va chorva haydab o'tish taqiqlanadi."),
    '3.9':    ("Velosipedda harakatlanish taqiqlangan",
               "Velosipedda va mopedda harakatlanish taqiqlanadi."),
    '3.10':   ("Piyodaning harakatlanishi taqiqlangan",
               "Piyodalarning harakatlanishi taqiqlanadi."),
    '3.11':   ("Vazn cheklangan",
               "Haqiqiy umumiy vazni belgida ko'rsatilganidan ortiq bo'lgan transport vositalarining harakatlanishi taqiqlanadi."),
    '3.12':   ("O'qqa tushadigan og'irlik cheklangan",
               "Har qanday o'qiga tushadigan haqiqiy og'irlik belgida ko'rsatilganidan ortiq bo'lgan transport vositalarining harakatlanishi taqiqlanadi."),
    '3.13':   ("Cheklangan balandlik",
               "Gabarit balandligi belgida ko'rsatilgandan ortiq bo'lgan transport vositalarining harakatlanishi taqiqlanadi."),
    '3.14':   ("Cheklangan kenglik",
               "Gabarit kengligi belgida ko'rsatilganidan ortiq bo'lgan transport vositalarining harakatlanishi taqiqlanadi."),
    '3.15':   ("Cheklangan uzunlik",
               "Gabarit uzunligi belgida ko'rsatilganidan ortiq bo'lgan transport vositalarining harakatlanishi taqiqlanadi."),
    '3.16':   ("Eng kam oraliq",
               "Belgida ko'rsatilganidan kam bo'ylama oraliq masofada harakatlanish taqiqlanadi."),
    '3.17.1': ("Bojxona",
               "Bojxona (nazorat punkti) oldida to'xtamasdan o'tib ketish taqiqlanadi."),
    '3.17.2': ("Xavf-xatar",
               "Yo'l-transport hodisasi, avariya, yong'in yoki boshqa xavf-xatar tufayli barcha transport vositalarining harakatlanishi taqiqlanadi."),
    '3.17.3': ("Nazorat joyi",
               "Transport vositalarining tekshirib o'tkazilishi majburiy bo'lgan nazorat punktlarida o'rnatiladi."),
    '3.18.1': ("O'ngga burilish taqiqlangan",
               "O'ngga burilish taqiqlanadi."),
    '3.18.2': ("Chapga burilish taqiqlanadi",
               "Chapga burilish taqiqlanadi."),
    '3.19':   ("Qayrilish taqiqlangan",
               "Qayrilish (U-turn) taqiqlanadi."),
    '3.20':   ("Quvib o'tish taqiqlangan",
               "Soatiga 40 km dan kam tezlikda harakatlanayotgan transport vositasidan boshqa transport vositalarini quvib o'tish taqiqlanadi."),
    '3.21':   ("Quvib o'tish taqiqlangan hududning oxiri",
               "Quvib o'tish taqiqlangan hududning tugashini bildiradi."),
    '3.22':   ("Yuk avtomobillarida quvib o'tish taqiqlangan",
               "To'liq vazni 3,5 tonnadan ortiq bo'lgan yuk avtomobillarida barcha transport vositalarini quvib o'tish taqiqlanadi."),
    '3.23':   ("Yuk avtomobillarida quvib o'tish taqiqlangan hududning oxiri",
               "Yuk avtomobillarida quvib o'tish taqiqlangan hududning tugashini bildiradi."),
    '3.24':   ("Yuqori tezlik cheklangan",
               "Belgida ko'rsatilganidan ortiq tezlikda (km/s) harakatlanish taqiqlanadi."),
    '3.25':   ("Yuqori tezlik cheklangan hududning oxiri",
               "Tezlik cheklangan hududning tugashini bildiradi."),
    '3.26':   ("Tovush moslamalaridan foydalanish taqiqlangan",
               "Yo'l transport hodisasining oldini olish hollaridan boshqa vaziyatlarda tovush moslamasidan foydalanish taqiqlanadi."),
    '3.27':   ("To'xtash taqiqlangan",
               "Transport vositalarining to'xtashi va to'xtab turishi taqiqlanadi."),
    '3.28':   ("To'xtab turish taqiqlangan",
               "Transport vositalarining to'xtab turishi taqiqlanadi."),
    '3.29':   ("Oyning toq kunlarida to'xtab turish taqiqlangan",
               "Oyning toq kunlarida to'xtab turish taqiqlanadi."),
    '3.30':   ("Oyning juft kunlarida to'xtab turish taqiqlangan",
               "Oyning juft kunlarida to'xtab turish taqiqlanadi."),
    '3.31':   ("Barcha cheklovlarning oxiri",
               "3.16, 3.20, 3.22, 3.24, 3.26—3.30 belgilaridan bir nechtasiga bir vaqtda amal qiladigan hududlarning oxiri."),
    '3.32':   ("Xavfli yuk tashiyotgan transport vositasining harakati taqiqlangan",
               "Xavfli yuk tashiyotgan transport vositasining harakatlanishi taqiqlanadi."),
    '3.33':   ("Portlovchi va tez alangalanuvchi yuk taqiqlangan",
               "Portlovchi va tez alangalanuvchi yukni tashiyotgan transport vositasining harakatlanishi taqiqlanadi."),
    '3.34':   ("Individual harakatlanish vositalarini boshqarish taqiqlangan",
               "Elektr skuter, segvey va shunga o'xshash individual harakatlanish vositalarini boshqarish taqiqlanadi."),
    '3.35':   ("Taqiqlovchi belgi (qo'shimcha)",
               "Qo'shimcha taqiqlovchi belgi."),

    # ── 4. Buyuruvchi ─────────────────────────────────────────────────────────
    '4.1.1':  ("Harakatlanish to'g'riga",
               "Faqat to'g'ri yo'nalishda harakatlanishga ruxsat etiladi."),
    '4.1.2':  ("Harakatlanish o'ngga",
               "Faqat o'ngga burilishga ruxsat etiladi."),
    '4.1.3':  ("Harakatlanish chapga",
               "Faqat chapga burilishga ruxsat etiladi."),
    '4.1.4':  ("Harakatlanish to'g'riga yoki o'ngga",
               "To'g'ri va o'ngga yo'nalishda harakatlanishga ruxsat etiladi."),
    '4.1.5':  ("Harakatlanish to'g'riga yoki chapga",
               "To'g'ri va chapga yo'nalishda harakatlanishga ruxsat etiladi."),
    '4.1.6':  ("Harakatlanish o'ngga yoki chapga",
               "O'ng va chap yo'nalishlarda harakatlanishga ruxsat etiladi."),
    '4.2.1':  ("To'siqni chapdan aylanib o'tish",
               "To'siqni faqat chap tomondan aylanib o'tishga ruxsat etiladi."),
    '4.2.2':  ("To'siqni o'ngdan aylanib o'tish",
               "To'siqni faqat o'ng tomondan aylanib o'tishga ruxsat etiladi."),
    '4.2.3':  ("To'siqni o'ngdan yoki chapdan aylanib o'tish",
               "To'siqni har qaysi tomondan aylanib o'tishga ruxsat etiladi."),
    '4.3':    ("Aylanma harakatlanish",
               "Ko'rsatkichlar yo'nalishlarida (soat miliga teskari) harakatlanishga ruxsat etiladi."),
    '4.4':    ("Yengil avtomobillar harakati",
               "Yengil avtomobillar, avtobus, mototsikllar va ruxsat etilgan to'liq vazni 3,5 tonnadan oshmaydigan yuk avtomobillari harakatlanishiga ruxsat etiladi."),
    '4.5':    ("Velosiped yo'lkasi",
               "Faqat velosiped va individual harakatlanish vositalarida harakatlanishga ruxsat etiladi."),
    '4.6':    ("Piyodalar yo'lkasi",
               "Faqat piyodalar yurishiga ruxsat etiladi."),
    '4.6.1':  ("Piyodalar, velosipedchilar va IHV birgalikdagi yo'lak",
               "Piyodalar, velosipedchilar va individual harakatlanish vositalarining birgalikdagi harakati tashkil etilgan yo'lak."),
    '4.6.2':  ("Piyodalar, velosipedchilar va IHV birgalikdagi yo'lakning oxiri",
               "Piyodalar, velosipedchilar va individual harakatlanish vositalarining birgalikdagi harakati tashkil etilgan yo'lakning oxiri."),
    '4.6.3':  ("Piyodalar, velosipedchilar va IHV alohida yo'lak",
               "Piyodalar va velosipedchilarning harakati alohida tashkil etilgan yo'lak."),
    '4.6.4':  ("Piyodalar, velosipedchilar va IHV alohida yo'lakning oxiri",
               "Piyodalar va velosipedchilarning harakati alohida tashkil etilgan yo'lakning oxiri."),
    '4.6.5':  ("Piyodalar, velosipedchilar va IHV alohida yo'lak (variant)",
               "Piyodalar, velosipedchilar va individual harakatlanish vositalarining harakati alohida tashkil etilgan yo'lak (variant)."),
    '4.6.6':  ("Piyodalar, velosipedchilar va IHV alohida yo'lakning oxiri (variant)",
               "Piyodalar, velosipedchilar va individual harakatlanish vositalarining harakati alohida tashkil etilgan yo'lakning oxiri (variant)."),
    '4.7':    ("Eng kam tezlik",
               "Faqat belgida ko'rsatilgan yoki undan yuqori tezlikda (km/soat) harakatlanishga ruxsat etiladi."),
    '4.8':    ("Eng kam tezlik belgilangan yo'lning oxiri",
               "Eng kam tezlik talabi amal qiladigan hududning tugashini bildiradi."),
    '4.9.1':  ("Xavfli yuk — yo'nalish to'g'riga",
               "'Xavfli yuk' tanish belgisi bilan jihozlangan transport vositalarining to'g'ri yo'nalishda harakatlanishiga ruxsat etiladi."),
    '4.9.2':  ("Xavfli yuk — yo'nalish chapga",
               "'Xavfli yuk' tanish belgisi bilan jihozlangan transport vositalarining chapga harakatlanishiga ruxsat etiladi."),
    '4.9.3':  ("Xavfli yuk — yo'nalish o'ngga",
               "'Xavfli yuk' tanish belgisi bilan jihozlangan transport vositalarining o'ngga harakatlanishiga ruxsat etiladi."),

    # ── 5. Axborot-ko'rsatgich ────────────────────────────────────────────────
    '5.1':    ("Avtomagistral",
               "Yo'l harakati qoidalarining avtomagistrallarda harakatlanish tartibi o'rnatilgan yo'lni bildiradi."),
    '5.2':    ("Avtomagistralning oxiri",
               "Avtomagistral maqomidagi yo'lning tugashini bildiradi."),
    '5.3':    ("Avtomobillar uchun mo'ljallangan yo'l",
               "Faqat avtomobillar, avtobus hamda mototsikllar, mopedlar va skuterlarning harakatlanishi uchun mo'ljallangan yo'l."),
    '5.4':    ("Avtomobillar uchun mo'ljallangan yo'lning oxiri",
               "Avtomobillar uchun mo'ljallangan yo'lning tugashini bildiradi."),
    '5.5':    ("Bir tomonlama harakatli yo'l",
               "Transport vositalari butun kenglik bo'yicha bir yo'nalishda harakatlanadigan yo'l."),
    '5.6':    ("Bir tomonlama harakatli yo'lning oxiri",
               "Bir tomonlama harakatli yo'lning tugashini bildiradi."),
    '5.7.1':  ("Bir tomonlama harakatli yo'lga chiqish",
               "Harakatlanish bir tomonlama bo'lgan yo'lga yoki qatnov qismiga chiqish joyi."),
    '5.7.2':  ("Bir tomonlama harakatli yo'lga chiqish (chap)",
               "Chap tomondan bir tomonlama harakatli yo'lga chiqish joyi."),
    '5.8.1':  ("Tasmalar bo'yicha harakat yo'nalishi",
               "Tasmalar soni va har biri bo'yicha ruxsat etilgan harakatlanish yo'nalishlari."),
    '5.8.2':  ("Tasma bo'yicha harakatlanish yo'nalishi",
               "Tasma bo'yicha ruxsat etilgan harakatlanish yo'nalishi."),
    '5.8.3':  ("Tasmaning boshlanishi (qo'shimcha)",
               "Yo'lning sekinlashish bo'lagi yoki balandlikka ko'tarilishdagi qo'shimcha tasmaning boshlanish qismi."),
    '5.8.4':  ("Tasmaning boshlanishi (o'rta)",
               "Uch tasmali yo'llarda o'rta tasma qismining boshlanishi."),
    '5.8.5':  ("Tasma oxiri (qo'shimcha)",
               "Balandlikka ko'tarilishdagi qo'shimcha tasmaning yoki tezlanish tasmaning oxiri."),
    '5.8.6':  ("Tasma oxiri (o'rta)",
               "Uch tasmali yo'llarda o'rta tasma qismining oxiri."),
    '5.8.7':  ("Tasmalar bo'yicha harakatlanish yo'nalishi",
               "Tasmalar bo'yicha ruxsat etilgan yoki taqiqlangan harakatlanish yo'nalishlarini bildiradi."),
    '5.8.8':  ("Tasmalar bo'yicha harakatlanish yo'nalishi (variant)",
               "Tasmalar bo'yicha harakatlanish yo'nalishlarining ikkinchi varianti."),
    '5.8.9':  ("Tasmalar bo'yicha harakatlanish yo'nalishi (qo'shimcha)",
               "Tasmalar bo'yicha harakatlanish yo'nalishlarining qo'shimcha varianti."),
    '5.9':    ("Yo'nalishli transport vositalari uchun mo'ljallangan tasma",
               "Yo'nalishli transport vositalari uchun ajratilgan tasmani bildiradi."),
    '5.10.1': ("Yo'nalishli TV uchun alohida tasma bor yo'l",
               "Yo'nalishli transport vositalarining umumiy oqimga qarshi harakatlanishi uchun ajratilgan tasmani bildiradi."),
    '5.10.2': ("Yo'nalishli TV uchun alohida tasma bor yo'lga chiqish",
               "Yo'nalishli transport vositalari uchun ajratilgan tasmasi bor yo'lga chiqish."),
    '5.10.3': ("Yo'nalishli TV uchun alohida tasma bor yo'lga chiqish (variant)",
               "Yo'nalishli transport vositalari uchun ajratilgan tasmasi bor yo'lga chiqishning ikkinchi varianti."),
    '5.10.4': ("Yo'nalishli TV uchun alohida tasma bor yo'lning oxiri",
               "Yo'nalishli transport vositalari uchun alohida tasma bor yo'lning oxiri."),
    '5.11.1': ("Qayrilib olish joyi",
               "Chapga burilish taqiqlangan yo'lda qayrilib olish joyi."),
    '5.11.2': ("Qayrilib olish oralig'i",
               "Qayrilib olish oralig'ining uzunligini bildiradi."),
    '5.12':   ("Avtobus va (yoki) trolleybus to'xtash joyi",
               "Avtobus va trolleybus to'xtash joyi."),
    '5.13':   ("Tramvay to'xtash joyi",
               "Tramvay to'xtash joyi."),
    '5.14':   ("Yo'nalishsiz taksilar to'xtab turish joyi",
               "Yo'nalishsiz taksilarning to'xtab turish joyi."),
    '5.15':   ("To'xtab turish joyi",
               "Transport vositalarining to'xtab turish joyi."),
    '5.15.1': ("Pullik to'xtab turish joyi",
               "To'lov asosida foydalaniladigan to'xtab turish joyi."),
    '5.15.2': ("Yer usti avtomobil qo'yish joyi",
               "Yer usti ko'p qavatli avtomobil qo'yish joyi."),
    '5.15.3': ("Yer osti avtomobil qo'yish joyi",
               "Yer osti (parking) avtomobil qo'yish joyi."),
    '5.15.4': ("Elektr quvvatlashli avtomobil qo'yish joyi",
               "Elektr avtomobillarni quvvatlash imkoniyati bilan to'xtab turish joyi."),
    '5.16.1': ("Piyodalar o'tish joyi (chap)",
               "Piyodalar o'tish joyining chap chegarasi."),
    '5.16.2': ("Piyodalar o'tish joyi (o'ng)",
               "Piyodalar o'tish joyining o'ng chegarasi."),
    '5.17.1': ("Piyodalarning yer ostidan o'tish joyi",
               "Piyodalarning yer ostidan o'tish joyi."),
    '5.17.2': ("Piyodalarning yer ostidan o'tish joyi (variant)",
               "Piyodalarning yer ostidan o'tish joyining o'ng tomondagi belgisi."),
    '5.17.3': ("Piyodalarning yer ustidan o'tish joyi",
               "Piyodalarning yer ustidan o'tish joyi."),
    '5.17.4': ("Piyodalarning yer ustidan o'tish joyi (variant)",
               "Piyodalarning yer ustidan o'tish joyining o'ng tomondagi belgisi."),
    '5.18':   ("Tavsiya etilgan tezlik",
               "Yo'lning shu qismida tavsiya etilgan harakatlanish tezligini bildiradi."),
    '5.19.1': ("Oxiri berk yo'l (to'g'ri)",
               "Yo'lning to'g'ri yo'nalishda oxiri berk ekanligini bildiradi."),
    '5.19.2': ("Oxiri berk yo'l (o'ngga)",
               "Yo'lning o'ng yo'nalishda oxiri berk ekanligini bildiradi."),
    '5.19.3': ("Oxiri berk yo'l (chapga)",
               "Yo'lning chap yo'nalishda oxiri berk ekanligini bildiradi."),
    '5.19.4': ("Oxiri berk yo'l (variant)",
               "Oxiri berk yo'lning qo'shimcha varianti."),
    '5.20.1': ("Yo'nalishlarning dastlabki ko'rsatkichi",
               "Belgida ko'rsatilgan aholi punkti va boshqa manzillarga harakatlanish yo'nalishini bildiradi."),
    '5.20.2': ("Yo'nalishlarning dastlabki ko'rsatkichi (variant)",
               "Yo'nalishlarning dastlabki ko'rsatkichining ikkinchi varianti."),
    '5.20.3': ("Harakatlanish chizmasi",
               "Chorrahada ruxsat etilgan harakatlanish yo'nalishini bildiradi."),
    '5.20.4': ("Burilish yoki qayrilib olish yo'nalish ko'rsatkichi",
               "Bir sathda kesishmaydigan yo'l qismlarida burilish va qayrilib olish yo'nalishini ko'rsatadi."),
    '5.20.5': ("Xizmat ko'rsatish maydoni",
               "Xizmat ko'rsatish maydoni joylashuvini bildiradi."),
    '5.21.1': ("Yo'nalish ko'rsatkichi",
               "Ko'rsatilgan manzillarga harakatlanish yo'nalishini bildiradi."),
    '5.21.2': ("Yo'nalishlar ko'rsatkichi",
               "Bir nechta manzillarga harakatlanish yo'nalishlarini bildiradi."),
    '5.22':   ("Aholi punktining boshlanishi",
               "Aholi punktlarida harakatlanish tartibini belgilovchi talablarga amal qilinadigan joyning nomi va boshlanishini bildiradi."),
    '5.23':   ("Aholi punktining oxiri",
               "Aholi punktlarida harakatlanish tartib-talablari bekor qilingan joyni bildiradi."),
    '5.23.1': ("Aholi punktining oxiri (variant 1)",
               "Aholi punktining oxiri belgisining birinchi varianti."),
    '5.23.2': ("Aholi punktining oxiri (variant 2)",
               "Aholi punktining oxiri belgisining ikkinchi varianti."),
    '5.24':   ("Aholi punktining boshlanishi (tartib tatbiq etilmaydi)",
               "Aholi punktlarida harakatlanish tartibini belgilovchi talablarga amal qilinmaydigan joyning nomi va boshlanishini bildiradi."),
    '5.24.1': ("Aholi punktining boshlanishi — variant 1",
               "Aholi punkti boshlanishining birinchi varianti."),
    '5.24.2': ("Aholi punktining boshlanishi — variant 2",
               "Aholi punkti boshlanishining ikkinchi varianti."),
    '5.25':   ("Aholi punktining oxiri (5.24 ga mos)",
               "5.24 yo'l belgisi bilan ko'rsatilgan aholi punktining oxiri."),
    '5.26':   ("Manzil nomi",
               "Aholi punktlaridan boshqa manzillarning nomini bildiradi (daryo, ko'l, dovon va boshqalar)."),
    '5.27':   ("Masofalar ko'rsatkichi",
               "Yo'nalish bo'yicha joylashgan aholi punktlarigacha bo'lgan masofani bildiradi (km)."),
    '5.28':   ("Kilometr belgisi",
               "Yo'lning boshi yoki oxirigacha bo'lgan masofani bildiradi (km)."),
    '5.29.1': ("Yo'l raqami",
               "Yo'lga berilgan raqamni bildiradi."),
    '5.29.2': ("Yo'l raqami va yo'nalishi",
               "Yo'lning raqami va yo'nalishini bildiradi."),
    '5.30.1': ("Yuk avtomobillari uchun harakat yo'nalishi (1)",
               "Chorrahada yuk avtomobillari uchun tavsiya etilgan birinchi harakatlanish yo'nalishi."),
    '5.30.2': ("Yuk avtomobillari uchun harakat yo'nalishi (2)",
               "Chorrahada yuk avtomobillari uchun tavsiya etilgan ikkinchi harakatlanish yo'nalishi."),
    '5.30.3': ("Yuk avtomobillari uchun harakat yo'nalishi (3)",
               "Chorrahada yuk avtomobillari uchun tavsiya etilgan uchinchi harakatlanish yo'nalishi."),
    '5.31':   ("Aylanib o'tish tasviri",
               "Harakatlanish uchun vaqtincha yopib qo'yilgan yo'l qismini chetlab o'tish chizmasi."),
    '5.32':   ("Chetlab o'tish yo'nalishi",
               "Vaqtincha yopib qo'yilgan yo'l qismini chetlab o'tish yo'nalishi."),
    '5.32.1': ("Chetlab o'tish yo'nalishi (o'ngga)",
               "O'ng tomonga chetlab o'tish yo'nalishi."),
    '5.32.2': ("Chetlab o'tish yo'nalishi (to'g'ri va o'ngga)",
               "To'g'ri va o'ng tomonga chetlab o'tish yo'nalishi."),
    '5.32.3': ("Chetlab o'tish yo'nalishi (variant)",
               "Chetlab o'tish yo'nalishining qo'shimcha varianti."),
    '5.33':   ("To'xtash chizig'i",
               "Svetoforning taqiqlovchi ishorasida transport vositalari to'xtaydigan joyni bildiradi."),
    '5.34':   ("Qayta tizilishning boshlang'ich ko'rsatkichi",
               "Ajratuvchi bo'lagi bo'lgan yo'lda harakatlanish yo'nalishini bildiradi."),
    '5.34.1': ("Qayta tizilishning boshlang'ich ko'rsatkichi (1)",
               "Boshqa qatnov qismiga qayta tizilishning boshlang'ich ko'rsatkichi."),
    '5.34.2': ("Qayta tizilishning boshlang'ich ko'rsatkichi (2)",
               "Boshqa qatnov qismiga qayta tizilishning boshlang'ich ko'rsatkichining ikkinchi varianti."),
    '5.35':   ("Reversiv harakatlanish",
               "Bir yoki bir necha tasmalarda harakatlanish yo'nalishi qarama-qarshi tomonga o'zgarishi mumkin bo'lgan yo'l qismining boshlanishi."),
    '5.36':   ("Reversiv harakatlanishning oxiri",
               "Reversiv harakatlanish qismining tugashini bildiradi."),
    '5.37':   ("Reversiv harakatlanish yo'liga chiqish",
               "Reversiv harakatlanish yo'liga chiqish joyi."),
    '5.38':   ("Turar joy dahasi",
               "Yo'l harakati qoidalarining turar joy dahalarida harakatlanish tartibi o'rnatilgan yo'l."),
    '5.39':   ("Turar joy dahasining oxiri",
               "Turar joy dahasining tugashini bildiradi."),
    '5.40':   ("Falokatli holatlar uchun kirish yo'li",
               "Falokatli holatlarda foydalaniladigan yo'l."),
    '5.41':   ("Foto va video qayd etish",
               "Haydovchilar qoidalarga rioya etishi elektron qurilmalar yordamida nazorat qilinayotganligini bildiradi."),
    '5.42':   ("Qizil chiroqda o'ngga harakatlanish",
               "Svetoforning taqiqlovchi ishorasi yonib turganda o'ngga burilishga ruxsat etilishini bildiradi."),
    '5.43':   ("Radar",
               "Belgilangan tezlikka rioya etish radarlar yordamida nazorat qilinayotganligini bildiradi."),
    '5.44':   ("Velosipedchilar va IHV uchun tasma",
               "Velosipedchilar va individual harakatlanish vositalari uchun ajratilgan tasmani bildiradi."),
    '5.45':   ("Velosipedchilar va IHV uchun tasmaning oxiri",
               "Velosipedchilar va individual harakatlanish vositalari uchun tasmaning tugashini bildiradi."),
    '5.46':   ("Maktab",
               "Maktab yoki maktabgacha ta'lim tashkilotlari oldida o'rnatiladi."),
    '5.47':   ("Turizm obyektlari yo'nalish ko'rsatgichi",
               "Turizm obyektlari joylashgan manzillarga harakatlanish yo'nalishlarini bildiradi."),
    '5.47.1': ("Turizm obyektlari",
               "Turizm obyekti joylashuvini bildiradi."),
    '5.47.2': ("Turizm axborot markazi",
               "Turizm axborot markazi joylashuvini bildiradi."),
    '5.48':   ("Baland piyodalar o'tish joyi",
               "Ko'tarilgan (baland) piyodalar o'tish joyi. 5.16.1-5.16.2 yo'l belgilari bilan birga qo'llaniladi."),

    # ── 6. Servis ─────────────────────────────────────────────────────────────
    '6.1':    ("Tibbiy yordam ko'rsatish joyi",
               "Birinchi tibbiy yordam ko'rsatish punkti joylashuvini bildiradi."),
    '6.2':    ("Shifoxona",
               "Shifoxona joylashuvini bildiradi."),
    '6.3.1':  ("Avtomobillarga yonilg'i quyish shoxobchasi",
               "Yonilg'i quyish shoxobchasi joylashuvini bildiradi."),
    '6.3.2':  ("Ko'p tarmoqli yonilg'i quyish shoxobchasi",
               "Bir necha turdagi yonilg'i beriladigan shoxobcha joylashuvini bildiradi."),
    '6.3.3':  ("Elektromobillarni quvvatlash shaxobchasi",
               "Elektr avtomobillarni quvvatlash stantsiyasi joylashuvini bildiradi."),
    '6.4':    ("Avtomobillarga texnik xizmat ko'rsatish joyi",
               "Avtomobillarga texnik xizmat ko'rsatish stansiyasi joylashuvini bildiradi."),
    '6.5':    ("Avtomobillarni yuvish joyi",
               "Avtomobil yuvish joyi joylashuvini bildiradi."),
    '6.6':    ("Telefon",
               "Telefon joylashuvini bildiradi."),
    '6.7':    ("Oshxona",
               "Oshxona joylashuvini bildiradi."),
    '6.8':    ("Ichimlik suvi",
               "Ichimlik suvi joylashuvini bildiradi."),
    '6.9':    ("Mehmonxona yoki motel",
               "Mehmonxona yoki motel joylashuvini bildiradi."),
    '6.10':   ("Kemping",
               "Kemping joylashuvini bildiradi."),
    '6.11':   ("Dam olish joyi",
               "Dam olish joyi joylashuvini bildiradi."),
    '6.12':   ("YPX maskani",
               "Yo'l harakati xavfsizligi maskani joylashuvini bildiradi."),
    '6.13':   ("Avtotashuvchilarning nazorat punkti",
               "Avtotashuvchilar uchun nazorat punkti joylashuvini bildiradi."),
    '6.14':   ("Hojatxona",
               "Hojatxona joylashuvini bildiradi."),
    '6.15':   ("Chiqindi yig'ish joyi",
               "Chiqindi yig'ish joyi joylashuvini bildiradi."),
    '6.16':   ("Cho'milish havzasi",
               "Cho'milish havzasi joylashuvini bildiradi."),
    '6.17':   ("Ichki ishlar bo'limi",
               "Ichki ishlar bo'limi joylashuvini bildiradi."),
    '6.18':   ("Radio aloqasi",
               "Radio aloqa stantsiyasi joylashuvini bildiradi."),
    '6.19':   ("Jome' masjidi",
               "Jome' masjidi joylashuvini bildiradi."),
    '6.20':   ("Cherkov",
               "Cherkov joylashuvini bildiradi."),
    '6.21':   ("Ibodatxona",
               "Ibodatxona joylashuvini bildiradi."),
    '6.22':   ("Temir yo'l vokzali",
               "Temir yo'l vokzali joylashuvini bildiradi."),
    '6.23':   ("Aeroport",
               "Aeroport joylashuvini bildiradi."),
    '6.24':   ("Bozor",
               "Bozor joylashuvini bildiradi."),
    '6.25':   ("Turistik axborot markazi",
               "Turistik axborot markazi joylashuvini bildiradi."),
    '6.26':   ("Qo'riqxona",
               "Qo'riqxona yoki muhofaza etilgan hudud joylashuvini bildiradi."),
    '6.27':   ("Manzarali joy",
               "Manzarali joy joylashuvini bildiradi."),
    '6.28':   ("Me'morchilik yodgorligi",
               "Me'morchilik yodgorligi joylashuvini bildiradi."),

    # ── 7. Qo'shimcha axborot ─────────────────────────────────────────────────
    '7.1.1':  ("Obyektgacha bo'lgan masofa",
               "Belgidan yo'lning xavfli joyi, cheklovlar kiritiladigan joyi yoki oldindagi muayyan joygacha bo'lgan masofani ko'rsatadi."),
    '7.1.2':  ("Obyektgacha bo'lgan masofa (chorraha)",
               "Chorrahagacha bo'lgan masofani ko'rsatadi."),
    '7.1.3':  ("Obyektgacha bo'lgan masofa (yo'ldan chetda, o'ngda)",
               "Yo'lning o'ng tomonida joylashgan manzilgacha bo'lgan masofani bildiradi."),
    '7.1.4':  ("Obyektgacha bo'lgan masofa (yo'ldan chetda, chapda)",
               "Yo'lning chap tomonida joylashgan manzilgacha bo'lgan masofani bildiradi."),
    '7.2.1':  ("Ta'sir oralig'i",
               "Ogohlantiruvchi belgilar bilan belgilangan xavfli joyning uzunligini yoki belgilarning ta'sir oralig'ini ko'rsatadi."),
    '7.2.2':  ("Ta'sir oralig'i (boshlanishi)",
               "3.27—3.30 taqiqlovchi belgilarining ta'siri saqlangan oraliqni ko'rsatadi."),
    '7.2.3':  ("Ta'sir oralig'i (oxiri)",
               "3.27—3.30 taqiqlovchi belgilarining ta'sir oralig'i oxirini ko'rsatadi."),
    '7.2.4':  ("Ta'sir oralig'i (oraliq)",
               "Haydovchilarga ularning 3.27—3.30 yo'l belgilari ta'sir doirasida ekanliklarini bildiradi."),
    '7.2.5':  ("Ta'sir oralig'i va yo'nalishi (o'ng)",
               "To'xtash taqiqlangan belgining ta'sir oralig'i va yo'nalishini ko'rsatadi."),
    '7.2.6':  ("Ta'sir oralig'i va yo'nalishi (chap)",
               "To'xtash taqiqlangan belgining ta'sir oralig'i va yo'nalishini ko'rsatadi."),
    '7.3.1':  ("Ta'sir yo'nalishi (to'g'ri)",
               "To'g'ri yo'nalishdagi ta'sir yo'nalishini ko'rsatadi."),
    '7.3.2':  ("Ta'sir yo'nalishi (o'ng)",
               "O'ng yo'nalishdagi ta'sir yo'nalishini ko'rsatadi."),
    '7.3.3':  ("Ta'sir yo'nalishi (chap)",
               "Chap yo'nalishdagi ta'sir yo'nalishini ko'rsatadi."),
    '7.4.1':  ("Transport turi: yuk avtomobillari",
               "Belgining ta'siri yuk tashuvchi transport vositalariga tatbiq etilishini ko'rsatadi."),
    '7.4.2':  ("Transport turi: traktorlar",
               "Belgining ta'siri traktorlarga tatbiq etilishini ko'rsatadi."),
    '7.4.3':  ("Transport turi: yengil avtomobillar",
               "Belgining ta'siri yengil avtomobillarga tatbiq etilishini ko'rsatadi."),
    '7.4.4':  ("Transport turi: avtobus",
               "Belgining ta'siri avtobuslarga tatbiq etilishini ko'rsatadi."),
    '7.4.5':  ("Transport turi: mototsikl",
               "Belgining ta'siri mototsikllarga tatbiq etilishini ko'rsatadi."),
    '7.4.6':  ("Transport turi: velosiped",
               "Belgining ta'siri velosipedlarga tatbiq etilishini ko'rsatadi."),
    '7.4.7':  ("Transport turi: yo'nalishli transport",
               "Belgining ta'siri yo'nalishli transport vositalariga tatbiq etilishini ko'rsatadi."),
    '7.4.8':  ("Transport turi: tirkamali transport",
               "Belgining ta'siri tirkamali transport vositalariga tatbiq etilishini ko'rsatadi."),
    '7.4.9':  ("Transport turi: elektromobillar",
               "Belgining ta'siri elektromobillarga tatbiq etilishini ko'rsatadi."),
    '7.4.10': ("Transport turi: yo'nalishsiz taksi",
               "Belgining ta'siri yo'nalishsiz taksilarga tatbiq etilishini ko'rsatadi."),
    '7.5.1':  ("Shanba, yakshanba va bayram kunlari",
               "Belgi shanba, yakshanba va rasmiy bayram kunlari amal qilishini ko'rsatadi."),
    '7.5.2':  ("Ish kunlari",
               "Belgi ish kunlari amal qilishini ko'rsatadi."),
    '7.5.3':  ("Hafta kunlari",
               "Belgiga haftaning qaysi kunlari amal qilinishini ko'rsatadi."),
    '7.5.4':  ("Amal qilish vaqti",
               "Belgiga kunning qaysi vaqtida amal qilishini ko'rsatadi."),
    '7.5.5':  ("Amal qilish vaqti (hafta kuni + soat)",
               "Belgiga haftaning qaysi kuni va qaysi soatlarida amal qilishini ko'rsatadi."),
    '7.5.6':  ("Amal qilish vaqti (variant 2)",
               "Belgiga amal qilish vaqtining ikkinchi varianti."),
    '7.5.7':  ("Amal qilish vaqti (variant 3)",
               "Belgiga amal qilish vaqtining uchinchi varianti."),
    '7.6.1':  ("To'xtab turish usuli: yo'l bo'yida",
               "Barcha turdagi transport vositalarini yo'lning qatnov qismida, trotuar yoniga qo'yish usuli."),
    '7.6.2':  ("To'xtab turish usuli: parallel",
               "Parallel holda trotuar yonida to'xtab turish usuli."),
    '7.6.3':  ("To'xtab turish usuli: 45° burchak",
               "45 daraja burchak ostida trotuar yonida to'xtab turish usuli."),
    '7.6.4':  ("To'xtab turish usuli: 90° burchak",
               "90 daraja burchak ostida trotuar yonida to'xtab turish usuli."),
    '7.6.5':  ("To'xtab turish usuli: qisman trotuar",
               "Qisman trotuar ustida to'xtab turish usuli."),
    '7.6.6':  ("To'xtab turish usuli: trotuar ustida",
               "Trotuar ustida to'xtab turish usuli."),
    '7.6.7':  ("To'xtab turish usuli: 45° trotuar",
               "45 daraja burchak ostida trotuar yonida to'xtab turish usuli."),
    '7.6.8':  ("To'xtab turish usuli: 90° trotuar",
               "90 daraja burchak ostida trotuar yonida to'xtab turish usuli."),
    '7.6.9':  ("To'xtab turish usuli: qo'shimcha",
               "Qo'shimcha to'xtab turish usuli."),
    '7.7':    ("Dvigatelni ishlatmasdan to'xtab turish joyi",
               "To'xtab turish joyida transport vositalarining dvigatelini ishlatmasdan to'xtab turishiga ruxsat etilganligini ko'rsatadi."),
    '7.8':    ("Pulli xizmat ko'rsatish joyi",
               "To'lov asosida xizmat ko'rsatilishini bildiradi."),
    '7.9':    ("To'xtab turish muddati cheklangan",
               "To'xtab turish joyida transport vositalarining to'xtab turishining eng ko'p muddatini ko'rsatadi."),
    '7.10':   ("Avtomobillarni ko'rikdan o'tkazish joyi",
               "Estakada yoki ko'zdan kechirish chuqurchalari borligini bildiradi."),
    '7.11':   ("Ruxsat etilgan to'la vazni cheklangan",
               "Belgining ta'siri ruxsat etilgan to'la vazni ko'rsatilgan miqdordan ortiq bo'lgan transport vositalariga taalluqli ekanligini ko'rsatadi."),
    '7.12':   ("Xavfli yo'l yoqasi",
               "Yo'l ishlari sababli yo'l yoqasiga chiqish xavfli ekanligi haqida ogohlantiradi."),
    '7.13':   ("Asosiy yo'lning yo'nalishi",
               "Chorrahada asosiy yo'lning yo'nalishini ko'rsatadi."),
    '7.14':   ("Harakatlanish tasmasi",
               "Belgi yoki svetofor ta'siridagi harakatlanish bo'lagini ko'rsatadi."),
    '7.15':   ("Ko'zi ojiz piyodalar",
               "Piyodalar o'tish joyidan ko'zi ojiz piyodalar foydalanishi mumkinligi haqida ogohlantiradi."),
    '7.16':   ("Nam qoplama",
               "Belgi qatnov qismining qoplamasi nam bo'lgan vaqtda ta'sir etishini ko'rsatadi."),
    '7.17':   ("Nogironlar",
               "To'xtab turish joyi nogironligi bo'lgan shaxslarning transport vositalari uchun ajratilganligini ko'rsatadi."),
    '7.18':   ("Nogironlar mustasno",
               "Belgilarning ta'siri nogironlik belgisi o'rnatilgan transport vositalariga joriy etilmaydi."),
    '7.19':   ("Foto va video qayd etish",
               "Yo'l harakati ishtirokchilarining harakatlari maxsus avtomatlashtirilgan qayd etish texnika vositalari orqali qayd etilayotganligini bildiradi."),
    '7.20':   ("Xavfli yuk toifasi",
               "Xavfli yuk toifasining raqamini ko'rsatadi."),
    '7.21':   ("Evakuator ishlamoqda",
               "Taqiqlovchi belgilar ta'sir oralig'ida to'xtagan transport vositalari majburiy evakuatsiya qilinishini ko'rsatadi."),
    '7.21.1': ("Evakuator ishlamoqda (variant 1)",
               "Evakuatorning ishlashi haqida birinchi variant belgi."),
    '7.21.2': ("Evakuator ishlamoqda (variant 2)",
               "Evakuatorning ishlashi haqida ikkinchi variant belgi."),
    '7.21.3': ("Evakuator ishlamoqda (variant 3)",
               "Evakuatorning ishlashi haqida uchinchi variant belgi."),
    '7.22.1': ("To'siq (o'ngga og'ish)",
               "Haydovchilarga to'siqning uzoqdan ko'rinishini ta'minlash uchun o'rnatiladi, o'ngga og'ish."),
    '7.22.2': ("To'siq (chapga og'ish)",
               "Haydovchilarga to'siqning uzoqdan ko'rinishini ta'minlash uchun o'rnatiladi, chapga og'ish."),
    '7.22.3': ("To'siq (ikki tomonlama)",
               "Haydovchilarga to'siqning uzoqdan ko'rinishini ta'minlash uchun ikki tomonlama o'rnatiladi."),
    '7.23':   ("Navbat bilan o'tish",
               "Transport vositalarining navbat bilan o'tishini bildiradi."),
    '7.24':   ("Transport vositasining davlat raqami",
               "Belgining ta'siri faqat ko'rsatilgan davlat raqamiga ega transport vositasiga joriy etiladi."),
    '7.25':   ("Faqat xizmat avtomobillari",
               "Belgining ta'siri faqat xizmat avtomobillariga joriy etilishini ko'rsatadi."),
    '7.26':   ("Sun'iy notekislik",
               "Belgining ta'siri sun'iy notekislik bo'lgan joyga joriy etilishini ko'rsatadi."),
}

# ─── Yo'l chiziqlari (r1 — gorizontal, r2 — vertikal) ────────────────────────
MARKINGS = {
    # Gorizontal (1.1 — 1.34)
    '1.1':    ("Uzluksiz o'q chizig'i",
               "Qarama-qarshi yo'nalishlarda harakatlanayotgan transport oqimlarini ajratadi; yo'lning xavfli joylaridagi harakatlanish bo'lagi chegarasini bildiradi."),
    '1.2':    ("Qatnov qismi chetini bildiruvchi uzluksiz chiziq",
               "Avtomagistrallarda qatnov qismi chetini bildiradi."),
    '1.3':    ("Ikki uzluksiz chiziq",
               "To'rt va undan ortiq harakatlanish bo'lagi bo'lgan yo'llarda qarama-qarshi yo'nalishdagi transport vositalari oqimini ajratadi."),
    '1.4':    ("To'xtash taqiqlangan joydagi chiziq",
               "To'xtash taqiqlangan joyni bildiradi. 3.27 belgisi bilan qo'llaniladi. Sariq rangda bo'ladi."),
    '1.5':    ("Yo'l ajratuvchi uzilgan chiziq",
               "Ikki yoki uch tasmali yo'llarda qarama-qarshi yo'nalishlarda harakatlanayotgan transport vositalari oqimlarini ajratadi; tasmalarning chegaralarini bildiradi."),
    '1.6':    ("Yaqinlashish chizig'i",
               "Qarama-qarshi yoki bir yo'nalishda harakatlanayotgan transport vositalari oqimlarini ajratuvchi uzluksiz chizig'iga yaqinlashayotganlik haqida ogohlantiradi."),
    '1.7':    ("Chorrahadagi tasmalarni bildiruvchi uzilgan chiziq",
               "Chorrahadagi harakatlanish tasmalarini bildiradi."),
    '1.8':    ("Tezlashish/sekinlashish bo'lagi chizig'i",
               "Tezlashish yoki sekinlashish bo'lagi bilan yo'lning qatnov qismidagi asosiy bo'lagi o'rtasidagi chegarani bildiradi."),
    '1.9':    ("Reversiv harakatlanish chizig'i",
               "Reversiv harakatlanish bo'laklarini ajratadi."),
    '1.10':   ("To'xtab turish taqiqlangan joydagi uzluksiz chiziq",
               "To'xtab turish taqiqlangan joyni bildiradi. 3.28 belgisi bilan qo'llaniladi. Sariq rangda bo'ladi."),
    '1.11':   ("Uzluksiz va uzilgan chiziq kombinatsiyasi",
               "Uzuq-uzuq chiziq tomonidan o'tish mumkin, uzluksiz chiziq tomonidan faqat quvib yoki aylanib o'tishni tugatayotganda o'tish mumkin."),
    '1.12':   ("\"Stop\" chizig'i",
               "Svetoforning (tartibga soluvchining) taqiqlovchi ishorasida transport vositalari to'xtaydigan joyni bildiradi."),
    '1.13':   ("\"Yo'l bering\" chizig'i",
               "Transport vositalarining 2.4 yoki 2.5 belgi talablariga muvofiq to'xtashi yoki yo'l berishi lozim bo'lgan joyni bildiradi."),
    '1.14.1': ("Piyoda o'tish yeri — 1-tur",
               "Piyodalar o'tish joyini belgilovchi zebra chiziqlari, 1-variant (oq rangda)."),
    '1.14.2': ("Piyoda o'tish yeri — 2-tur",
               "Piyodalar o'tish joyini belgilovchi zebra chiziqlari, 2-variant."),
    '1.14.3': ("Piyoda o'tish yeri — 3-tur",
               "Piyodalar o'tish joyini belgilovchi zebra chiziqlari, 3-variant."),
    '1.14.4': ("Maktab piyoda o'tish yeri",
               "Oq-qizil rangli yo'l chizig'i maktab va maktabgacha ta'lim muassasalari oldida piyodalarning o'tish joyini belgilaydi."),
    '1.15':   ("Velosiped yo'lkasi kesishuvi chizig'i",
               "Yo'lning velosiped yo'lkasi kesib o'tgan joyini bildiradi."),
    '1.16.1': ("Yo'naltiruvchi orolcha — 1-tur",
               "Transport vositalari oqimi ajraladigan yoki qo'shiladigan joylardagi yo'naltiruvchi orolchalarni bildiradi."),
    '1.16.2': ("Yo'naltiruvchi orolcha — 2-tur",
               "Transport vositalari oqimi qo'shiladigan joylardagi yo'naltiruvchi orolchalarni bildiradi."),
    '1.16.3': ("Yo'naltiruvchi orolcha — 3-tur",
               "Transport vositalari oqimi ayriladigan joylardagi yo'naltiruvchi orolchalarni bildiradi."),
    '1.17':   ("Avtobus va taksi to'xtash yeri chizig'i",
               "Yo'nalishli transport vositalarining bekatlari hamda taksilarning to'xtab turish joylarini bildiradi. Sariq rangda bo'ladi."),
    '1.18':   ("Tasma yo'nalishi ko'rsatkichi",
               "Chorrahada tasmalar bo'yicha ruxsat etilgan harakatlanish yo'nalishlarini ko'rsatadi."),
    '1.19':   ("Torayish ogohlantiruv chizig'i",
               "Qatnov qismining toraygan joyiga yaqinlashganlik haqida ogohlantiruvchi chiziq."),
    '1.20':   ("\"Yo'l bering\" ogohlantiruv chizig'i",
               "Haydovchini 1.13 chizig'iga yaqinlashayotgani haqida ogohlantiradi."),
    '1.21':   ("\"STOP\" yozuvi",
               "2.5 belgisi bilan birga qo'llanilganda haydovchini to'xtash chizig'iga yaqinlashayotganligi haqida ogohlantiradi."),
    '1.22':   ("Yo'l (harakatlanish yo'nalishi) raqami",
               "Yo'l yoki harakatlanish yo'nalishi raqamini ko'rsatadi."),
    '1.23':   ("Yo'nalishli transport vositalari bo'lagi chizig'i",
               "Yo'lning faqat yo'nalishli transport vositalari uchun mo'ljallangan bo'lagini bildiradi."),
    '1.24':   ("Nogironlar uchun to'xtab turish joyi",
               "Nogironligi bo'lgan shaxslarning avtotransport vositalari uchun to'xtab turish joyi."),
    '1.25':   ("Piyoda yo'lkasi chizig'i",
               "Piyodalar yo'lkasini yoki piyodalar va velosipedchilar birgalikda harakatlanishi mo'ljallangan yo'lkaning piyodalar uchun mo'ljallangan qismini bildiradi."),
    '1.26':   ("Velosiped yo'lkasi chizig'i",
               "Velosiped yo'lkasini yoki velosiped harakatlanishi uchun mo'ljallangan tasmani bildiradi."),
    '1.27':   ("Ogohlantiruvchi belgini takrorlovchi chiziq",
               "Ogohlantiruvchi yo'l belgilarini takrorlovchi yo'l chizig'i."),
    '1.28':   ("Taqiqlovchi belgini takrorlovchi chiziq",
               "Taqiqlovchi yo'l belgilarini takrorlovchi yo'l chizig'i."),
    '1.29':   ("Sun'iy yo'l notekisligi chizig'i",
               "Sun'iy yo'l notekisligini bildiradi."),
    '1.29.1': ("Baland piyoda o'tish joyi chizig'i",
               "Sun'iy notekislik — baland piyodalar o'tish joyini bildiradi."),
    '1.29.2': ("3D ko'rinishdagi baland piyoda o'tish joyi",
               "Avtomobil yo'llarida '3D' ko'rinishdagi baland piyodalar o'tish joyini bildiradi."),
    '1.29.3': ("3D ko'rinishdagi piyoda o'tish joyi",
               "Avtomobil yo'llarida '3D' ko'rinishdagi piyodalar o'tish joyi."),
    '1.30':   ("Maktab yaqinidagi ogohlantiruvchi chiziq",
               "Maktablar joylashgan hududlar oldida maktab o'quvchilarning chiqib qolish ehtimolini inobatga olgan holda chiziladi."),
    '1.31':   ("Shovqin chiziqlari",
               "Tez harakatlanadigan xavfli burilishlar va piyodalar o'tish joylariga yaqinlashuvda haydovchilar hushyorligini oshirish maqsadida qo'llaniladi."),
    '1.32':   ("Choraha kesishmasi hududi chizig'i",
               "Qatnov qismi kesishmasi hududiga yaqinlashayotganligini anglatuvchi chiziq."),
    '1.33':   ("Gorizontal yo'l chizig'i — 1.33",
               "1.33-raqamli gorizontal yo'l chizig'i."),
    '1.34':   ("Gorizontal yo'l chizig'i — 1.34",
               "1.34-raqamli gorizontal yo'l chizig'i."),

    # Vertikal (2.1 — 2.8)
    '2.1':    ("Yo'l inshootlari tik elementlari belgilari",
               "Harakatlanayotgan transport vositalariga xavf tug'diradigan yo'l inshootlarining tik elementlari (ko'priklar, yo'l o'tkazgich va estakadalar, ustunlar) ni bildiradi."),
    '2.2':    ("Yo'l inshootlari pastki peshtoqlari belgilari",
               "Tunnellar, ko'priklar, yo'l o'tkazgich va estakadalarning pastki peshtoqini bildiradi."),
    '2.3':    ("Dumaloq ustunlar belgilari",
               "Ajratish mintaqalaridagi yoki xavfsizlik orolchalaridagi dumaloq ustunlarni bildiradi."),
    '2.4':    ("Yo'naltiruvchi ustunlar belgilari",
               "Yo'naltiruvchi, beton yoki temir beton ustunlar, to'siq tirgaklar va hokazolarni bildiradi."),
    '2.5':    ("Xavfli joylardagi to'siq yon yuzalari belgilari",
               "Yo'lning kichik radiusli burilish, tik nishablik va boshqa xavfli joylarda yo'l to'siqlarining yon yuzalarini bildiradi."),
    '2.6':    ("Boshqa joylardagi to'siq yon yuzalari belgilari",
               "Boshqa joylardagi to'siqlarning yon yuzalarini bildiradi."),
    '2.7':    ("Xavfli to'siq va xavfsizlik orolchalari belgilari",
               "Xavfli joylardagi to'siqni (bordyurni) va yo'l sathidan baland bo'lgan xavfsizlik orolchalarini bildiradi."),
    '2.8':    ("Vertikal yo'l chizig'i — 2.8",
               "2.8-raqamli vertikal yo'l chizig'i."),
}


# ─── Yordamchi funksiyalar ────────────────────────────────────────────────────

def _filename_to_number(stem: str) -> str:
    """
    z1_3_1  →  '1.3.1'
    z5_8_7  →  '5.8.7'
    r1_14_1 →  '1.14.1'
    r2_3    →  '2.3'
    """
    parts   = stem.split('_')
    prefix  = parts[0]            # 'z1', 'z8', 'r1', 'r2' ...
    section = prefix[1:]          # strip leading letter ('z' or 'r')
    rest    = parts[1:]
    return '.'.join([section] + rest)


def _get_sign_data(prefix: str, number: str):
    """(name_uzl, description_uzl) qaytaradi."""
    # Yo'l chiziqlari (r1, r2)
    if prefix.startswith('r'):
        return MARKINGS.get(number, (f"{number} — chizig'i", ''))

    # Vaqtincha belgilar (z8): original belgining nomi + " (vaqtincha)"
    if prefix == 'z8':
        # '8.1.8' → '1.8';  '8.3.18.1' → '3.18.1'
        parts    = number.split('.')
        original = '.'.join(parts[1:])
        orig     = SIGNS.get(original)
        if orig:
            return f"{orig[0]} (vaqtincha)", orig[1]
        return f"{number} (vaqtincha)", ''

    # Odatiy belgilar (z1–z7, z9–z11)
    return SIGNS.get(number, (f"{number} — belgisi", ''))


def _src_dir(base: Path, prefix: str) -> Path:
    return base / ('rules_r' if prefix.startswith('r') else 'signs_z')


# ─── Command ─────────────────────────────────────────────────────────────────

class Command(BaseCommand):
    help = "signs_z/ va rules_r/ papkasidagi rasmlardan SignSection va Sign modellarini to'ldiradi"

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear', action='store_true',
            help='Mavjud barcha Sign va SignSection larni o\'chib qaytadan yuklaydi'
        )

    def handle(self, *args, **options):
        base_dir = Path(settings.BASE_DIR)
        dst_dir  = Path(settings.MEDIA_ROOT) / 'signs'
        dst_dir.mkdir(parents=True, exist_ok=True)

        if options['clear']:
            Sign.objects.all().delete()
            SignSection.objects.all().delete()
            self.stdout.write(self.style.WARNING("Eski ma'lumotlar o'chirildi."))

        total_sections = 0
        total_signs    = 0
        total_skipped  = 0

        for sec_data in SECTIONS:
            prefix   = sec_data['prefix']
            src      = _src_dir(base_dir, prefix)

            section, created = SignSection.objects.get_or_create(
                order=sec_data['order'],
                defaults={
                    'name_uzl': sec_data['name_uzl'],
                    'name_uzk': sec_data['name_uzk'],
                    'name_ru':  sec_data['name_ru'],
                },
            )
            if created:
                total_sections += 1
                self.stdout.write(f"  Bo'lim yaratildi: {section.name_uzl}")

            if src.exists():
                images = sorted(src.glob(f'{prefix}_*'))
            else:
                images = sorted(dst_dir.glob(f'{prefix}_*'))

            for order_idx, img_path in enumerate(images, start=1):
                stem   = img_path.stem
                number = _filename_to_number(stem)
                dst    = dst_dir / img_path.name

                if src.exists() and not dst.exists():
                    shutil.copy2(img_path, dst)

                name_uzl, desc_uzl = _get_sign_data(prefix, number)

                if Sign.objects.filter(section=section, number=number).exists():
                    total_skipped += 1
                    continue

                Sign.objects.create(
                    section         = section,
                    number          = number,
                    name_uzl        = name_uzl,
                    image           = f'signs/{img_path.name}',
                    description_uzl = desc_uzl,
                    order           = order_idx,
                )
                total_signs += 1

        self.stdout.write(self.style.SUCCESS(
            f"\nNatija: {total_sections} bo'lim, {total_signs} belgi yaratildi, "
            f"{total_skipped} ta mavjud bo'lgani tufayli o'tkazib yuborildi."
        ))
