# Generated by Django 6.0.4 on 2026-04-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_multilingual_and_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ticket_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='1–123 oraligidagi bilet (question_category)', null=True, verbose_name='Bilet raqami'),
        ),
    ]
