# Generated by Django 6.0.4 on 2026-04-30 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_add_mode_timelimit_to_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='mode',
            field=models.CharField(choices=[('category', "Kategoriya bo'yicha"), ('test', 'Test (aralash)'), ('practice', 'Mashq')], default='category', max_length=10),
        ),
        migrations.CreateModel(
            name='SavedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saqlangan savol',
                'verbose_name_plural': 'Saqlangan savollar',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
