# Generated by Django 6.0.4 on 2026-05-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_examsession_mode_savedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='mode',
            field=models.CharField(choices=[('category', "Kategoriya bo'yicha"), ('test', 'Imtihon (aralash)'), ('marathon', 'Marafon'), ('practice', 'Mashq (random)')], default='category', max_length=10),
        ),
    ]
