# Generated by Django 6.0.4 on 2026-05-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_examsession_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='quiz.category')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategoriya javobi',
                'verbose_name_plural': 'Kategoriya javoblari',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
