# Generated by Django 6.0.4 on 2026-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_category_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='tokens_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='mode',
            field=models.CharField(choices=[('category', 'Mavzuli test'), ('mixed', 'Aralash test (10 savol)'), ('marathon', 'Marafon'), ('test', 'Sinov exam'), ('practice', 'Mashq (random)')], default='category', max_length=10),
        ),
    ]
