# Generated by Django 6.0.4 on 2026-05-08 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='reason',
            field=models.CharField(choices=[('initial_grant', "Boshlang'ich token"), ('daily_bonus', 'Kunlik bonus'), ('monthly_grant', 'Oylik token'), ('subscription', 'Obuna bonusi'), ('category_spend', 'Mavzuli test (sarflash)'), ('category_refund', 'Mavzuli test (qaytarish)'), ('category_bonus', 'Mavzuli test (bonus)'), ('mixed_spend', 'Aralash test (sarflash)'), ('mixed_refund', 'Aralash test (qaytarish)'), ('mixed_bonus', 'Aralash test (bonus)'), ('marathon_spend', 'Marafon (sarflash)'), ('marathon_refund', 'Marafon (qaytarish)'), ('marathon_bonus', 'Marafon (bonus)'), ('exam_spend', 'Sinov exam (sarflash)'), ('exam_refund', 'Sinov exam (qaytarish)'), ('exam_bonus', 'Sinov exam (bonus)'), ('practice_spend', 'Mashq (sarflash)'), ('practice_refund', 'Mashq (qaytarish)'), ('contest_entry', 'Contest (kirish)'), ('contest_prize', 'Contest (sovrin)'), ('admin_adjust', 'Admin tomonidan')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro_monthly', 'Pro Monthly'), ('pro_yearly', 'Pro Yearly')], default='free', max_length=15)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_daily_bonus_at', models.DateField(blank=True, null=True)),
                ('last_monthly_grant_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
    ]
