# Generated by Django 6.0.4 on 2026-05-13 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def deduplicate_memberships(apps, schema_editor):
    """Bir user bir nechta akademiyada bo'lsa, eng oxirgisini qoldirib qolganini o'chiramiz.
    Bu OneToOneField constraint'i ishlashidan oldin majburiy.
    """
    AcademyMembership = apps.get_model('contests', 'AcademyMembership')
    from django.db.models import Count
    dupe_user_ids = (
        AcademyMembership.objects
        .values('user_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
        .values_list('user_id', flat=True)
    )
    for uid in dupe_user_ids:
        memberships = AcademyMembership.objects.filter(user_id=uid).order_by('-joined_at')
        latest = memberships.first()
        memberships.exclude(pk=latest.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_academy_standalone_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1) Dublikat memberships'larni tozalash (OneToOne dan oldin)
        migrations.RunPython(deduplicate_memberships, migrations.RunPython.noop),

        # 2) Eski unique_together olib tashlanadi
        migrations.AlterUniqueTogether(
            name='academymembership',
            unique_together=set(),
        ),

        # 3) user — OneToOneField (DB-level: 1 user → 1 akademiya)
        migrations.AlterField(
            model_name='academymembership',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='academy_membership',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='academyprofile',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='Username'),
        ),
    ]
