# Generated by Django 6.0.4 on 2026-04-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_add_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='quiz.category'),
        ),
    ]
