# Generated by Django 6.0.4 on 2026-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_add_category_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='mode',
            field=models.CharField(choices=[('category', "Kategoriya bo'yicha"), ('test', 'Test (aralash)')], default='category', max_length=10),
        ),
        migrations.AddField(
            model_name='examsession',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
