# Generated by Django 6.0.4 on 2026-05-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uzl', models.CharField(max_length=200, verbose_name='Nomi (UZL)')),
                ('name_uzk', models.CharField(blank=True, max_length=200, verbose_name='Nomi (UZK)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (RU)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Yo'l belgisi bo'limi",
                'verbose_name_plural': "Yo'l belgisi bo'limlari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Masalan: 1.1, 2.5', max_length=20, verbose_name='Raqami')),
                ('name_uzl', models.CharField(max_length=300, verbose_name='Nomi (UZL)')),
                ('name_uzk', models.CharField(blank=True, max_length=300, verbose_name='Nomi (UZK)')),
                ('name_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (RU)')),
                ('image', models.ImageField(upload_to='signs/', verbose_name='Rasm')),
                ('description_uzl', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZL)')),
                ('description_uzk', models.TextField(blank=True, verbose_name='Qisqa tavsif (UZK)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (RU)')),
                ('extra_uzl', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (UZL)")),
                ('extra_uzk', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (UZK)")),
                ('extra_ru', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (RU)")),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='signs.signsection')),
            ],
            options={
                'verbose_name': "Yo'l belgisi",
                'verbose_name_plural': "Yo'l belgilari",
                'ordering': ['order', 'number'],
            },
        ),
    ]
