# Generated by Django 6.0.4 on 2026-05-10 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'lov admini",
                'verbose_name_plural': "To'lov adminlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('pro_monthly', 'Pro Monthly'), ('pro_yearly', 'Pro Yearly')], max_length=15)),
                ('amount_som', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Yaratildi'), ('awaiting', 'Fayl kutilmoqda'), ('pending', 'Tasdiqlash kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Bekor qilindi')], default='initiated', max_length=15)),
                ('payload_token', models.CharField(blank=True, max_length=24, unique=True)),
                ('user_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='payments/%Y/%m/')),
                ('file_telegram_id', models.CharField(blank=True, max_length=255)),
                ('file_kind', models.CharField(blank=True, help_text='photo / document', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='payments.paymentadmin')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['user', '-created_at'], name='payments_pa_user_id_7a85fd_idx')],
            },
        ),
    ]
