# Generated by Django 6.0.4 on 2026-05-02 05:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hamyon',
                'verbose_name_plural': 'Hamyonlar',
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('initial_grant', "Boshlang'ich token"), ('category_spend', 'Kategoriya (sarflash)'), ('category_refund', 'Kategoriya (qaytarish)'), ('exam_spend', 'Imtihon (sarflash)'), ('exam_refund', 'Imtihon (qaytarish)'), ('exam_bonus', 'Imtihon (bonus)'), ('marathon_spend', 'Marafon (sarflash)'), ('marathon_refund', 'Marafon (qaytarish)'), ('marathon_bonus', 'Marafon (bonus)'), ('practice_spend', 'Mashq (sarflash)'), ('practice_refund', 'Mashq (qaytarish)'), ('contest_entry', 'Contest (kirish)'), ('contest_prize', 'Contest (sovrin)'), ('admin_adjust', 'Admin tomonidan')], max_length=30)),
                ('session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contest_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tokens.tokenwallet')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
