# Generated by Django 6.0.4 on 2026-05-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_pricing_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='reason',
            field=models.CharField(choices=[('initial_grant', "Boshlang'ich token"), ('daily_bonus', 'Kunlik bonus'), ('monthly_grant', 'Oylik token'), ('subscription', 'Obuna bonusi'), ('category_spend', 'Mavzuli test (sarflash)'), ('category_refund', 'Mavzuli test (qaytarish)'), ('category_bonus', 'Mavzuli test (bonus)'), ('mixed_spend', 'Aralash test (sarflash)'), ('mixed_refund', 'Aralash test (qaytarish)'), ('mixed_bonus', 'Aralash test (bonus)'), ('marathon_spend', 'Marafon (sarflash)'), ('marathon_refund', 'Marafon (qaytarish)'), ('marathon_bonus', 'Marafon (bonus)'), ('exam_spend', 'Sinov exam (sarflash)'), ('exam_refund', 'Sinov exam (qaytarish)'), ('exam_bonus', 'Sinov exam (bonus)'), ('practice_spend', 'Mashq (sarflash)'), ('practice_refund', 'Mashq (qaytarish)'), ('practice_bonus', 'Mashq (bonus)'), ('contest_entry', 'Contest (kirish)'), ('contest_prize', 'Contest (sovrin)'), ('admin_adjust', 'Admin tomonidan')], max_length=30),
        ),
    ]
