# Generated by Django 6.0.4 on 2026-04-20 22:50

from django.db import migrations


def empty_email_to_null(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(empty_email_to_null, migrations.RunPython.noop),
    ]
