# Generated by Django 6.0.4 on 2026-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_existing_empty_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fake',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soxta foydalanuvchi'),
        ),
    ]
